### ISSUE TITLE
Syntax only parsed on save.

### ISSUE THREAD

**Issue by julienvincent** [reasonml-old/vim-reason-loader#1]
As I understand, this is a wrapper around other reason tooling and so I am not sure if this is the correct place to open an issue - please point me at the right place if this is not it.

Syntax errors are only re-parsed after write (`:w`). This means that even if the syntax or type error has been resolved, it still reports the old error until a write occurs. The behavior here I think should be to re-parse on key-change, maybe after a debounce.

**Comment by jordwalke** [comment]
I believe this may be the behavior of Syntastic. Can you check if there's a configuration for Syntastic that ends up doing what you want?

**Comment by julienvincent** [comment]
Thanks - I checked up on Syntastic and as far as I can see, this behavior can't be changed 👎 Nothing to be done I suppose - closing.
